[custom_commands]
"add to megamerge" = {args = ["rebase", "-r", "@", "-A", "main", "-B", "megamerge"]}
"remove selected from megamerge" = {args = ["rebase", "-s", "megamerge", "-d", "all:megamerge- ~$change_id"]}
"rebase all" = {args = ["rebase", "-b", "megamerge", "-d", "main"]}
"new main" = {args = ["new", "main"]}
"resolve mergiraf" = {key = ["R"], args = ["resolve", "--tool", "mergiraf", "-r", "$change_id"]}
"fix" = {key = ["F"], args = ["fix"]}
